# Generated by Django 5.2.7 on 2025-10-26 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modellog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_logs', to='project.project'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='project.project'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='project.project'),
        ),
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='project.project'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='project.question'),
        ),
        migrations.AddField(
            model_name='siliconeperson',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silicone_people', to='project.project'),
        ),
        migrations.AddField(
            model_name='response',
            name='silicone_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='project.siliconeperson'),
        ),
        migrations.AddField(
            model_name='modellog',
            name='silicone_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='project.siliconeperson'),
        ),
    ]
