# Generated by Django 5.2.7 on 2025-10-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='gpt_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
