# Generated by Django 5.2.7 on 2025-11-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_response_gpt_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
