# Generated by Django 5.2.7 on 2025-11-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='project',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='project.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='method',
            field=models.CharField(blank=True, help_text='Analysis method (sentiment, correlation, etc.)', max_length=100, null=True),
        ),
    ]
