# Generated by Django 5.2.7 on 2025-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_analysisresult_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='gpt_answer',
            field=models.BooleanField(default=False),
        ),
    ]
