# Generated by Django 5.2.7 on 2025-11-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_unique_user_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siliconeperson',
            old_name='political_orientation',
            new_name='church_goer',
        ),
        migrations.RemoveField(
            model_name='siliconeperson',
            name='conditioning_text',
        ),
        migrations.RemoveField(
            model_name='siliconeperson',
            name='skin_color',
        ),
        migrations.AddField(
            model_name='siliconeperson',
            name='discuss_politics',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='siliconeperson',
            name='ideology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siliconeperson',
            name='party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siliconeperson',
            name='political_interest',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='siliconeperson',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
