# Generated by Django 5.2.7 on 2025-11-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_political_orientation_siliconeperson_church_goer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siliconeperson',
            name='patriotism',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='siliconeperson',
            name='real_vote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
