# Generated by Django 5.2.7 on 2025-11-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_siliconeperson_patriotism_siliconeperson_real_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siliconeperson',
            name='ideological',
        ),
    ]
