# Generated by Django 5.2.7 on 2025-12-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_siliconeperson_ideological'),
    ]

    operations = [
        migrations.AddField(
            model_name='siliconeperson',
            name='id_str',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
