# Generated by Django 5.2.7 on 2025-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_siliconeperson_dataset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siliconeperson',
            name='id_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
