# Generated by Django 5.2.7 on 2025-12-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_siliconeperson_id_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_analysed',
            field=models.BooleanField(default=False),
        ),
    ]
