# Generated by Django 5.2.7 on 2025-12-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_prompt_question_prompt_silicone_person_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
