/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLayoutStudiesRouteImport } from './routes/_authLayout/studies'
import { Route as AuthLayoutPriceCalculatorRouteImport } from './routes/_authLayout/price-calculator'
import { Route as AuthLayoutHomeRouteImport } from './routes/_authLayout/home'
import { Route as AuthLayoutCreateStudyRouteImport } from './routes/_authLayout/create-study'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutStudiesRoute = AuthLayoutStudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutPriceCalculatorRoute =
  AuthLayoutPriceCalculatorRouteImport.update({
    id: '/price-calculator',
    path: '/price-calculator',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const AuthLayoutHomeRoute = AuthLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutCreateStudyRoute = AuthLayoutCreateStudyRouteImport.update({
  id: '/create-study',
  path: '/create-study',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/create-study': typeof AuthLayoutCreateStudyRoute
  '/home': typeof AuthLayoutHomeRoute
  '/price-calculator': typeof AuthLayoutPriceCalculatorRoute
  '/studies': typeof AuthLayoutStudiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/create-study': typeof AuthLayoutCreateStudyRoute
  '/home': typeof AuthLayoutHomeRoute
  '/price-calculator': typeof AuthLayoutPriceCalculatorRoute
  '/studies': typeof AuthLayoutStudiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authLayout/create-study': typeof AuthLayoutCreateStudyRoute
  '/_authLayout/home': typeof AuthLayoutHomeRoute
  '/_authLayout/price-calculator': typeof AuthLayoutPriceCalculatorRoute
  '/_authLayout/studies': typeof AuthLayoutStudiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/create-study'
    | '/home'
    | '/price-calculator'
    | '/studies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/create-study'
    | '/home'
    | '/price-calculator'
    | '/studies'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/login'
    | '/signup'
    | '/_authLayout/create-study'
    | '/_authLayout/home'
    | '/_authLayout/price-calculator'
    | '/_authLayout/studies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/studies': {
      id: '/_authLayout/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof AuthLayoutStudiesRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/price-calculator': {
      id: '/_authLayout/price-calculator'
      path: '/price-calculator'
      fullPath: '/price-calculator'
      preLoaderRoute: typeof AuthLayoutPriceCalculatorRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/home': {
      id: '/_authLayout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthLayoutHomeRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/create-study': {
      id: '/_authLayout/create-study'
      path: '/create-study'
      fullPath: '/create-study'
      preLoaderRoute: typeof AuthLayoutCreateStudyRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutCreateStudyRoute: typeof AuthLayoutCreateStudyRoute
  AuthLayoutHomeRoute: typeof AuthLayoutHomeRoute
  AuthLayoutPriceCalculatorRoute: typeof AuthLayoutPriceCalculatorRoute
  AuthLayoutStudiesRoute: typeof AuthLayoutStudiesRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutCreateStudyRoute: AuthLayoutCreateStudyRoute,
  AuthLayoutHomeRoute: AuthLayoutHomeRoute,
  AuthLayoutPriceCalculatorRoute: AuthLayoutPriceCalculatorRoute,
  AuthLayoutStudiesRoute: AuthLayoutStudiesRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
